package li2latex.template

object TemplateConstants {
  val PERSON_NAME_TEMPLATE = "%PERSON_NAME_TEMPLATE%"

  val SECTIONS_CONTAINER_TEMPLATE = "%SECTIONS_CONTAINER_TEMPLATE%"

  val PERSON_NAME = "%PERSON_NAME%"

  val ALL_SECTIONS = "%ALL_SECTIONS%"

  val SECTION_TITLE = "%SECTION_TITLE%"

  val SECTION_CONTENT = "%SECTION_CONTENT%"

  val ITEM_CONTENT = "%ITEM_CONTENT%"

  val ITEM_TITLE = "%ITEM_TITLE%"

  val ITEM_SUBTITLE = "%ITEM_SUBTITLE%"

  val ITEM_DATE = "%ITEM_DATE%"

  val ITEM_LOC = "%ITEM_LOC%"

  val ALL_BULLET_ITEMS = "%ALL_BULLET_ITEMS%"

  val BULLET_ITEM = "%BULLET_ITEM%"

  val CONTACT_ADDRESS_LINE1 = "%CONTACT_ADDRESS_LINE1%"

  val CONTACT_ADDRESS_LINE2 = "%CONTACT_ADDRESS_LINE2%"

  val CONTACT_EMAIL = "%CONTACT_EMAIL%"

  val CONTACT_PHONE = "%CONTACT_PHONE%"
}
